export const PROFILE = {
    LOGIN_ACTION: 'LOGIN_ACTION',
    LOGIN_RESULT: 'LOGIN_RESULT',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS'
};

export const ADMIN = {
    QUERY_LIST_ACTION: 'QUERY_LIST_ACTION',
    QUERY_LIST_RESULT_ACTION: 'QUERY_LIST_RESULT_ACTION',
};

