export const PROFILE = {
    LOGIN_ACTION: 'LOGIN_ACTION',
    LOGIN_RESULT: 'LOGIN_RESULT',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS'
};

export const ADMIN = {
    QUERY_LIST_ACTION: 'QUERY_LIST_ACTION',
    QUERY_LIST_RESULT_ACTION: 'QUERY_LIST_RESULT_ACTION',
    ADD_ADMIN_ACTION: 'ADD_ADMIN_ACTION',
    ADD_ADMIN_SUCCESS: 'ADD_ADMIN_SUCCESS',
    EDIT_ADMIN_ACTION: 'EDIT_ADMIN_ACTION'
};

